import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadSetupEnv, parseSetupEnv } from "./setup-env.js";

describe("setup env parser", () => {
  test("parses exported single-quoted values", () => {
    const parsed = parseSetupEnv("export KEYSTORE_PASSWORD='hunter2'\n");
    expect(parsed.KEYSTORE_PASSWORD).toBe("hunter2");
  });

  test("parses single quote escapes produced by setup writer", () => {
    const parsed = parseSetupEnv("export KEYSTORE_PASSWORD='pass'\"'\"'word'\n");
    expect(parsed.KEYSTORE_PASSWORD).toBe("pass'word");
  });

  test("ignores comments and blank lines", () => {
    const parsed = parseSetupEnv(
      [
        "# generated by setup",
        "",
        "export KEYSTORE_PASSWORD='abc'",
        "RPC_URL_1=https://eth.llamarpc.com",
        "",
      ].join("\n")
    );
    expect(parsed.KEYSTORE_PASSWORD).toBe("abc");
    expect(parsed.RPC_URL_1).toBe("https://eth.llamarpc.com");
  });
});

describe("setup env autoload", () => {
  test("loads nearest .grimoire/setup.env from current directory tree", async () => {
    const root = await mkdtemp(join(tmpdir(), "grimoire-setup-env-"));
    const project = join(root, "project");
    const nested = join(project, "nested", "dir");
    const setupDir = join(project, ".grimoire");
    await mkdir(setupDir, { recursive: true });
    await mkdir(nested, { recursive: true });
    await writeFile(join(setupDir, "setup.env"), "export KEYSTORE_PASSWORD='local-secret'\n");

    const env: Record<string, string | undefined> = {};
    const result = loadSetupEnv({ cwd: nested, env });

    expect(result.loadedKeys).toEqual(["KEYSTORE_PASSWORD"]);
    expect(env.KEYSTORE_PASSWORD).toBe("local-secret");

    await rm(root, { recursive: true, force: true });
  });

  test("does not override already-set environment variables", async () => {
    const root = await mkdtemp(join(tmpdir(), "grimoire-setup-env-"));
    const setupDir = join(root, ".grimoire");
    await mkdir(setupDir, { recursive: true });
    await writeFile(join(setupDir, "setup.env"), "export KEYSTORE_PASSWORD='from-file'\n");

    const env: Record<string, string | undefined> = {
      KEYSTORE_PASSWORD: "already-set",
    };
    const result = loadSetupEnv({ cwd: root, env });

    expect(result.loadedKeys).toEqual([]);
    expect(env.KEYSTORE_PASSWORD).toBe("already-set");

    await rm(root, { recursive: true, force: true });
  });
});
