/**
 * @grimoirelabs/core
 * Core compiler and runtime for Grimoire spell execution
 */

export type {
  ActionBuilder,
  AdvisoryBuilder,
  ComputeBuilder,
  ConditionalBuilder,
  EmitBuilder,
  HaltBuilder,
  LoopBuilder,
  ParallelBuilder,
  PipelineBuilder,
  SpellBuilder,
  TryBuilder,
  WaitBuilder,
} from "./builders/index.js";
// Builders
export {
  action,
  advisory,
  arrayAccess,
  binary,
  binding,
  call,
  compute,
  conditional,
  emit,
  forLoop,
  halt,
  literal,
  parallel,
  param,
  pipeline,
  propertyAccess,
  repeat,
  spell,
  tryBlock,
  until,
  wait,
} from "./builders/index.js";
export type {
  AdvisorySummary,
  IRGeneratorResult,
  ParseResult,
  TypeCheckResult,
  ValidationResult,
} from "./compiler/index.js";
// Compiler
export {
  compile,
  compileFile,
  parseExpression,
  parseSpell,
  typeCheckIR,
  validateIR,
} from "./compiler/index.js";
export type {
  AdvisoryHandler,
  AdvisoryHandlerInput,
  BreakerRecord,
  BreakerState,
  BuildTransactionsOptions,
  CircuitBreakerCheckResult,
  CircuitBreakerTriggerResult,
  CommitOptions,
  CreateContextOptions,
  CrossChainOrchestrationOptions,
  CrossChainOrchestrationResult,
  EvalContext,
  EvalValue,
  ExecuteOptions,
  PreviewOptions,
  RunMetrics,
  RunProvenance,
  RunRecord,
  SessionLedgerView,
  SessionMode,
  SessionPnlAssetView,
  SessionPnlView,
  SessionRunOptions,
  SessionRunResult,
  SqliteStateStoreOptions,
  StateStore,
  TimestampedEvent,
} from "./runtime/index.js";
// Runtime
export {
  buildTransactions,
  CircuitBreakerManager,
  commit,
  createContext,
  createRunRecord,
  evaluate,
  evaluateAsync,
  execute,
  getSessionLedgerView,
  getSessionPnlView,
  InMemoryLedger,
  injectHandoffParams,
  orchestrateCrossChain,
  preview,
  rejectReservedCrossChainParams,
  runManagedSession,
  runOneShotSession,
  runSession,
  SqliteStateStore,
  signReceipt,
  toCrossChainReceipt,
} from "./runtime/index.js";
// Types
export * from "./types/index.js";
// Venues
export { createVenueRegistry } from "./venues/index.js";
export type {
  OffchainExecutionResult,
  VenueAdapter,
  VenueAdapterContext,
  VenueAdapterMeta,
  VenueBuildMetadata,
  VenueBuildResult,
  VenueConstraint,
  VenueQuoteMetadata,
  VenueRegistry,
} from "./venues/types.js";
export type {
  BuiltTransaction,
  ExecutionMode,
  ExecutionResult as WalletExecutionResult,
  ExecutorOptions,
  GasEstimate,
  KeyConfig,
  KeySourceType,
  ProviderConfig,
  TransactionLog,
  TransactionReceipt,
  TransactionRequest,
  TransactionResult,
  Wallet,
} from "./wallet/index.js";
// Wallet
export {
  CHAIN_CONFIGS,
  createExecutor,
  createKeystore,
  createProvider,
  createTransactionBuilder,
  createWallet,
  createWalletFromConfig,
  createWalletFromMnemonic,
  Executor,
  formatGasCostUsd,
  formatWei,
  generatePrivateKey,
  getAddressFromConfig,
  getChainName,
  getNativeCurrencySymbol,
  isNativeCurrency,
  isTestnet,
  KeyLoadError,
  loadPrivateKey,
  Provider,
  TransactionBuilder,
} from "./wallet/index.js";
